### ISSUE TITLE
Task: Write unit tests for basic data acquisition in data_inlet.py

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#10]
### Description

Develop unit tests to validate the basic data acquisition functionality of the DataInlet class.

### Tasks

- [ ] Create mock LSL streams to simulate LSL stream behavior
     - [ ] Utilize StreamOutlet from pylsl
- [ ] Test data pulling
    - [ ] Verify that pull_sample() retrieves data correctly
    - [ ] Check the data buffer updates with new samples as expected
 - [ ] Test handling NaNs and no streams available
 - [ ] Test signal emission
    - [ ] Confirm that updated data signal emitted to the presenters is updated with the correct data when pulling a new sample
- [ ] Add Docstrings and typehints
