### ISSUE TITLE
Task: Define the IMainAppView interface in views/interfaces.py

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#11]
### Description

Establish the IMainAppView interface to outline the methods that the MainAppPresenter will interact with in the View component. This interface ensures a clear connection between the Presenter and the View, promoting testability through loose coupling

### Tasks

- [ ] Create interfaces.py in views/ directory
- [ ] Define the IMainAppView interface abstract methods
    - [ ] update_plot(data: dict) -> None
    - [ ] display_error(message: str) -> None
    - [ ] toggle_channel_visibility(channel_name: str, visible: bool) -> None
- [ ] Docstrings and typehints
