### ISSUE TITLE
Task: Define MainAppPresenter class in presenters presenters/main_app_presenter.py

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#12]
### Description

Develop the MainAppPresenter class, which acts as the Presenter in the MVP architecture. This class will handle interactions between the Model (DataInlet) and the View (MainAppWindow), and process user inputs.

### Tasks

- [ ] Implement the MainAppPresenter class
    - [ ]  Implement constructor to accept an instance of IMainAppView and a list of Datainlet instances
- [ ] Implement data handling methods to handle data from Datainlet and update the View
    - [ ] Define on_data_updated(self, source_id: str, data: dice) -> None:
- [ ] Implement visibility control methods
    - [ ] Define toggle_channel_visibility(self, channel_name: str, visible: bool) -> None:
- [ ] Establish connections to listen for updated data signals from each DataInlet
- [ ] Add Docstrings and typehints
