### ISSUE TITLE
Task: Implement on_data_updated() method in MainAppPresenter

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#13]
### Description

Implement the on_data_updated() method within the MainAppPresenter class to process incoming data from the Model and instruct the View to update the plots accordingly

### Tasks

- [ ] Implement a method that recieves source_id and data from DataInlet's signal
- [ ] Transform and validate the data before passing it to the View
- [ ] Call the update_plot() method on the view inteface with the new data
- [ ] Add Docstrings and typehints
- [ ] Unit Testing
    - [ ] Test that when on_data_updated() is called, the view's update_plot() method is invoked with the correct data
