### ISSUE TITLE
Task: Implement toggle_channel_visibility method in MainAppPresenter

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#14]
### Description

Develop the toggle_channel_visibility() method within the MainAppPresenter to handle user requests for showing or hiding specific channels and streams (two levels). This method will interact with the Model to update data acquisition and instruct the View to reflect the changes in the UI.

### Tasks

- [ ] Implement a method that accepts 'channel_name' and 'visible' parameters
- [ ] Instruct the corresponding DataInlet instances to toggle the visibility of the specific channel (channel_name)
- [ ] Update UI elements (checkboxes) to reflect visibility changes
- [ ] Docstrings and Unit tests, as always
