### ISSUE TITLE
Task: Implement __init__ method in MainAppWindow

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#16]
### Description

Implement the constructor for MainAppWindow class. Set up user interface, intialize plot widgets, and establish connections with the Presenter

### Tasks

- [ ] Call `super().__init__()` to ensure initialization of QMainWindow
- [ ] Set window title / size / arrangement order
- [ ] Instantiate a central widget
- [ ] Set up control panel with a QTreeWidget for managing streams and checkboxes
- [ ] Initialize plot widgets for each stream
- [ ] Connect signals 'itemChanged' to the appropriate handler
- [ ] Create an instance of MainAppPresenter, passing self and the list of DataInlet instances
