### ISSUE TITLE
Task: Implement event handlers for user interactions in MainAppWindow

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#19]
### Description

Develop event handler (toggling channel visibility). This handler will forward user action to the Presenter for processing

### Tasks

- [ ] Connect itemChanged signal to Handler ensuring that changes in the QTreeWidget checkboxes trigger the appropriate handler
- [ ] Implement the handle_item_changed() method
    - [ ] Determine whether the changed item is a stream or a channel
    - [ ] Forward the action to the Presenter by calling method `toggle_channel_visibility()`
