### ISSUE TITLE
Task: Implement the EEGPlotWindow class in views/eeg_plot_window.py

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#20]
### Description

Develop the EEGPlotWindow class to display all EEG channels within a single window. This class is an additional View in the MVP architecture, and is needed to separate channels into distinct plots.

### Tasks

- [ ] Develop EEGPlotWindow class, inheriting from QMainWindow
    - [ ] Ensure it implements the IEEGPlotWindow
    - [ ] Setup a grid layout to accomodate multiple plot widgets (varying n as # of channels can vary)
    - [ ] Initialize PlotWidget instances for each EEG channel 
- [ ] Define and initialize IEEGPlotWindow interface, outlining methods for updating individual EEG channel plots.
- [ ] Connect to Presenter
    - [ ] Instantiate an EEGPlotPresenter, passing the View and relevant DataInlet instances
- [ ] Docstrings and Unit tests
