### ISSUE TITLE
Task: Define EEGPlotPresenter in presenters/eeg_plot_presenter.py

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#21]
### Description

Develop the EEGPlotPresenter class, which acts as the Presenter for the EEGPlotWindow View. This class will handle the logic for updating individual EEG channel plots based on incoming data from the Model.

### Tasks

- [ ] Implement the EEGPlotPresenter Class
    - [ ] Implement constructor to accept an instance of IEEGPlotView and a list of Datainlet instances
- [ ] Implement data handling methods to handle data_updated signals from DataInlet and update the View
    - [ ] Define on_data_updated(self, source_id: str, data: dice) -> None:
- [ ] Implement visibility control methods
    - [ ] Define toggle_channel_visibility(self, channel_name: str, visible: bool) -> None:
- [ ]  Establish connections to listen for updated data signals from each DataInlet
- [ ] Docstrings and Unit tests
