### ISSUE TITLE
Task: Implement the update_eeg_channel() Method in EEGPlotPresenter

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#22]
### Description

Implement the update_eeg_channel() method within the EEGPlotPresenter class to process and forward data for individual EEG channels to the EEGPlotWindow View.

### Tasks

- [ ] Define the update_eeg_channel() Method, accepting channel_name and data as parameters
- [ ] Process the incoming data
- [ ] Update the View by calling the display_eeg_channel() method on the View interface
- [ ] Doctrings and Unit tests
