### ISSUE TITLE
Task: Implement the display_eeg_channel() Method in EEGPlotWindow

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#23]
### Description

Develop the display_eeg_channel() method within the EEGPlotWindow class to update individual EEG channel plots with new data received from the Presenter.

### Tasks

- [ ] Define the display_eeg_channel() method to accept channel_name and data as parameters
- [ ] Update specific Plot Widget by locating the corresponding PlotWidget for the given channel_name, and update the plot with the new data using the on_data_updated() method
- [ ] Handle plot refreshing, ensuring the plot updates in real-time
- [ ] Docstrings and Unit tests
