### ISSUE TITLE
Task: Update package metadata

### ISSUE THREAD

**Issue by Asanto32** [kimit0310/MoBI_GUI#27]
### Description

Prepare all package metadata for public release

### Tasks

- [ ] Finalize readme
- [ ] Deploy + link webpage
- [ ] publish to PyPI
- [ ] Change the name to MoBI-View
