### ISSUE TITLE
Task: Implement Basic Data Acquisition from LSL Streams in data_inlet.py

### ISSUE THREAD

**Issue by kimit0310** [kimit0310/MoBI_GUI#9]
### Description

Establish the basic capability to acquire data from LSL streams. This involves implementing a method that can successfully connect to an LSL stream and retrieve data samples. data_inlet will function as the model in the Model-View-Presenter architecture this GUI will take.

### Tasks

- [ ] Create DataInlet class structure, ensuring it inherits from QObjects from PyQt
- [ ] Implement `__init__` method
    - [ ] Initialize the LSL StreamInlet using the StreamInfo
    - [ ] Setup initial attributes, channel_names, channel_count, buffers, and ptr
- [ ] Implement `pull_sample()` method
    - [ ] Create a method to pull data samples from the LSL stream
    - [ ] Ensure that the method updates the buffer with samples
- [ ] Define connection schema to Presenters
- [ ] Add Docstrings and typehints
